const names = [
      "8 Sense",
      "AI Expert",
      "Adept Bomb Disposal Machine",
      "Adept Cultivation Entity",
      "Adept Encoding Droid",
      "Adept Planet Examination Golem",
      "Advanced Emergency Machine",
      "Advanced Evacuation Entity",
      "Advanced Safety Guard Bot",
      "Advanced Termination Device",
      "Advanced Trooper",
      "Artificial Instruction Android",
      "Artificial Repairation Golem",
      "Assembly Sentinel",
      "Atmospheric Bomb Enticer Apparatus",
      "Aura Generator Gizmo",
      "Automated Conqueror Machine",
      "Automated Evacuation Bot",
      "Automated Network Defense Bot",
      "Automated Planet Exploration Golem",
      "Automated Protection",
      "Automated Recording Machine",
      "Automated Usher Android",
      "Automatic Lab Partner Bot",
      "Automatic Personal Protection Device",
      "Automatic Planet Examination Device",
      "Autonomous Fire Fighting Technician",
      "Autonomous Ocean Exploration Emulator",
      "Autonomous Peacekeeping Robot",
      "Autonomous Probe Drone",
      "Autonomous Shepherd Cyborg",
      "Ballistic Fighter",
      "Bio-Electrionic Data Destruction Android",
      "Bio-Electrionic Decoding Cyborg",
      "Bio-Electrionic Guidance Technology",
      "Bio-Electrionic Planet Exploration Devi",
      "Bio-Electrionic Robot Control Entity",
      "Bio-Electrionic Sabotage Entity",
      "Bionic Science Golem",
      "Bionic Translation Machine",
      "Blackout Circulator Interface",
      "Bot Vile",
      "Broadcast Concealotron Apparatus",
      "Casualty Mobilizer Doohickey",
      "Chrome Warmech",
      "Compact Infiltration Prototype",
      "Conscious Oceanic Navigation Machine",
      "Conscious Planet Survey Drone",
      "Conscious Planetary Analysis Android",
      "Cybernated Expedition Juggernaut",
      "Cybernated Medical Droid",
      "Cybernated Planetary Analysis Device",
      "Cybernetic Animal Control Drone",
      "Cybernetic Emergency Repair Robot",
      "Cybernetic Observer Golem",
      "Cybernetic Planetary Expedition Golem",
      "Destroyer Of Worlds",
      "Digital Info Analyzing Golem",
      "Digital Nullification Juggernaut",
      "Digital Probe Juggernaut",
      "Digital Recording Entity",
      "Ditto Advanced",
      "Dream Alternator Network",
      "Dynamic Information Cyborg",
      "Efficient Data Collection Technician",
      "Efficient Eradication Technician",
      "Efficient Farming Automaton",
      "Efficient Home Protection Droid",
      "Electronic Safety Android",
      "Essential Exploration Cyborg",
      "Exceptional Assassination Prototype",
      "Exceptional Escort Prototype",
      "Exceptional Mapping Entity",
      "Exceptional Pilot Technology",
      "Exceptional War Management Android",
      "Experimental Examination Golem",
      "Experimental Farming Golem",
      "Experimental Home Protection Technology",
      "Extra-Terrestrial Shepherd Prototype",
      "Extraordinary Defence Enticer Widget",
      "Extraterrestial Bodyguard Automaton+",
      "Extraterrestial Docking Prototype",
      "Extreme Bodyguard Prototype",
      "Extreme Garbage Disposal Drone",
      "Extreme Garbage Disposal Technician",
      "Extreme Human Training Android",
      "Extreme Safety Guard Automaton",
      "Fury Mech",
      "GM UNIMATE",
      "General Emulation Machine",
      "General Processor Bot",
      "General War Domination Drone",
      "Global First Aid Robot",
      "Global Home Protection Technology",
      "Global Oceanic Navigation Android",
      "Global War Management Android",
      "Golem Guardian",
      "Grim Reaper",
      "HAL 9000",
      "Hell AI",
      "High-Powered Emulation Android",
      "High-Powered Invasion Emulator",
      "High-Powered Mining Automaton",
      "High-Powered Planetary Analysis Golem",
      "High-Powered Probe Technology",
      "Highpowered Lab Partner Automaton",
      "Highpowered Protection Machine",
      "Humanoid Data Protection Automaton",
      "Humanoid Laboratorium Automaton",
      "Humanoid Space Exploration Technician",
      "Imperial Decimator",
      "Independent Encryption Android",
      "Independent Instruction Drone",
      "Independent Pilot Technician",
      "Independent Transportation Golem",
      "Independent Troubleshooting Automaton",
      "Integrated Enforcer Cyborg",
      "Integrated Nullification Android",
      "Integrated Safety Prototype",
      "Integrated Travel Entity",
      "Integrated Usher Droid",
      "Intelligent Observer Automaton",
      "Intelligent Peacekeeping Emulator",
      "Intelligent Space Navigation Cyborg",
      "Intelligent Waste Collection Emulator",
      "Iron Angel",
      "Iron Walker",
      "LILLIPUT TOY ROBOT",
      "MQ-1 PREDATOR",
      "Main Battle Entity",
      "Main Escort Technology",
      "Main Safety Device",
      "Mechanical Examination Prototype",
      "Mechanical First Aid Machine",
      "Mechanical Oceanic Navigation Entity",
      "Mechanical Supervision Droid",
      "Mechanized Space Navigation Entity",
      "Motorized Eradication Android",
      "Motorized Instructor Technician",
      "Motorized Unit Response Cyborg",
      "Myriad Trooper",
      "Neohuman Harvesting Device",
      "Neohuman Laboratorium Automaton",
      "Neohuman Sanitation Cyborg",
      "Neohuman Supervision Technician",
      "Neohuman Waste Disposal Technician",
      "Nuclear Operating Automaton",
      "Perceptive Home Protection Robot",
      "Personal Planetary Expedition Bot",
      "Personal Regulation Bot",
      "Plane Panzer",
      "Preliminary Emulation Juggernaut",
      "Preliminary Human Control Android",
      "Primary Travel Robot",
      "Primary Usher Automaton",
      "Prime Waste Disposal Android",
      "Primitive Caretaker Juggernaut",
      "Primitive Farming Automaton",
      "Primitive First Aid Robot",
      "Primitive Processor Robot",
      "Programmed Algorithm Technician",
      "Programmed Care Emulator",
      "Programmed Neutralization Technology",
      "Programmed Spacecraft Defense Cyborg",
      "ROBART III",
      "ROOMBA DISCOVERY",
      "Rational Emergency Android",
      "Rational Emergency Repair Technician",
      "Rational First Aid Automaton",
      "Rational Utility Technician",
      "Reactive Animal Handling Robot",
      "Reactive Flora And Fauna Drone",
      "Reactive Garbage Disposal Entity",
      "Reactive Human Control Technology",
      "Reactive Lifeform Detection Entity",
      "Reactive Management Drone",
      "Reactive Personal Protection Technology",
      "Reactive Processor Emulator",
      "Reactive Waste Disposal Drone",
      "Ready to Rob-OT",
      "Responsive Diplomacy Technology",
      "Responsive Ocean Exploration Technician",
      "Responsive Planet Examination Droid",
      "Responsive Sabotage Golem",
      "Revered Command Unit",
      "Robotic Terraforming Cyborg",
      "Salvage Stalker",
      "Sci Bots",
      "Secondary Data Analyzing Bot",
      "Secondary Excretion Golem",
      "Secondary Planet Defence Machine",
      "Secondary War Domination Bot",
      "Self-Aware Encoding Device",
      "Self-Aware Info Collection Entity",
      "Self-Aware Unit Response Robot",
      "Self-Regulaing Enforcer Cyborg",
      "Self-Reliant Airplane Control Machine",
      "Self-Reliant Encryption Golem",
      "Self-Sufficient Expedition Droid",
      "Self-Sufficient Operation Entity",
      "Self-Sufficient Planet Examination Auto",
      "Self-Sufficient Robot Control Entity",
      "Selfaware Antivenom Manipulator Tool",
      "Selfaware Transport Diagnoser Apparatus",
      "Sensitive Construction Technology",
      "Sensitive Planetary Analysis Entity",
      "Sensory Diplomacy Juggernaut",
      "Sensory Repairation Android",
      "Shade Armor Suit",
      "Snap Engine",
      "Solar Care Technician",
      "Solar Diplomacy Entity",
      "Solar Teaching Robot",
      "Stealth Detector Apparatus",
      "Strange Thing",
      "Strategic Supervision Device",
      "Super Emergency Repair Technician",
      "Super Flora And Fauna Cyborg",
      "Super Nova",
      "Super Probe Cyborg",
      "Super Riot Control Juggernaut",
      "Supreme Care Emulator",
      "Supreme Escort Automaton",
      "Supreme Flora And Fauna Bot",
      "Synchronized Decoding Automaton",
      "Synchronized Emulation Machine",
      "Synchronized Evasion Golem",
      "Synchronized Processor Technician",
      "Synchronized Termination Emulator",
      "THE IRON GIANT",
      "THE TERMINATOR",
      "Temporary Inspection Technician",
      "Temporary Nullification Cyborg",
      "Temporary Termination Android",
      "Temporary Waste Disposal Emulator",
      "The Nawab",
      "Ultimate Decoding Emulator",
      "Ultimate Emergency Response Technician",
      "Ultimate Recording Prototype",
      "Ultimate Waste Disposal Droid",
      "Unified Emulation Emulator",
      "Universal Encryption Android",
      "Universal Exploration Golem",
      "Universal Safety Guard Technician",
      "Universal Space Exploration Golem",
      "Vile Drone",
      "Widow Maker"
]
export default names