const names = [
      "8 Sense",
      "AI Expert",
      "AIBO",
      "ALEXA",
      "Ace",
      "Adept Cultivation Entity",
      "Advanced Emergency Machine",
      "Advanced Evacuation Entity",
      "Advanced Safety Guard Bot",
      "Advanced Termination Device",
      "Advanced Trooper",
      "Aerowave",
      "Aeroworks",
      "AgentScript",
      "Albatross",
      "Alpha",
      "Angel",
      "Apex",
      "Artificial Instruction Android",
      "Assembly Sentinel",
      "Atmospheric Bomb Enticer Apparatus",
      "Aura Generator Gizmo",
      "Automated Conqueror Machine",
      "Automated Evacuation Bot",
      "Automated Protection",
      "Automated Recording Machine",
      "Automated Usher Android",
      "Autonomous Peacekeeping Robot",
      "Avalanche",
      "B.R.A.I.N",
      "Ballistic Fighter",
      "Beacon",
      "Behemoth",
      "Bigby",
      "Bio-Electrionic Data Destruction Android",
      "Bio-Electrionic Decoding Cyborg",
      "Bionic Science Golem",
      "Bionic Translation Machine",
      "Blackout Circulator Interface",
      "Bot Vile",
      "Boulder",
      "Brakesplitter",
      "Brarg",
      "Brigade",
      "Broadcast Concealotron Apparatus",
      "Bulk",
      "C3-P0",
      "CYBERMAN",
      "Carnage",
      "Casualty Mobilizer Doohickey",
      "Chrome Warmech",
      "Cluster",
      "Coil",
      "Comet",
      "Condor",
      "Conscious Planet Survey Drone",
      "Conscious Planetary Analysis Android",
      "Core",
      "Crayg",
      "Creature",
      "Cybernetic Animal Control Drone",
      "Cybernetic Emergency Repair Robot",
      "DALEK",
      "Daemon",
      "Daik",
      "Deepbolt",
      "Deepdrift",
      "Deftblitz",
      "Demise",
      "Destiny",
      "Destroyer Of Worlds",
      "Digital Probe Juggernaut",
      "Digital Recording Entity",
      "Ditto Advanced",
      "Dos",
      "Doublecrush",
      "Dread",
      "Dream Alternator Network",
      "Drist",
      "Dum",
      "Dune",
      "Dunewheels",
      "Duster",
      "Dusthorn",
      "Dynamic Information Cyborg",
      "ELEKTRO",
      "Efficient Data Collection Technician",
      "Electronic Safety Android",
      "Enigma",
      "Enugx",
      "Experimental Farming Golem",
      "Experimental Home Protection Technology",
      "Extraordinary Defence Enticer Widget",
      "Extraterrestial Bodyguard Automaton+",
      "Extreme Garbage Disposal Technician",
      "Extreme Human Training Android",
      "Fe",
      "Feral",
      "Freak",
      "Fury Mech",
      "G-Unit-102c",
      "GM UNIMATE",
      "GOOGLE",
      "GORT",
      "GU-82c",
      "GU-93x",
      "Gadget",
      "General War Domination Drone",
      "Geth-Unit-113e",
      "Geth-Unit-16x",
      "Geth-Unit-185s",
      "Geth-Unit-229b",
      "Geth-Unit-23a",
      "Geth-Unit-39s",
      "Geth-Unit-41b",
      "Geth-Unit-80s",
      "Global Home Protection Technology",
      "Golem Guardian",
      "Goliath",
      "Granite",
      "Granius",
      "Grim Reaper",
      "Grins",
      "Groove",
      "HAL 9000",
      "Hell AI",
      "Hercules",
      "High-Powered Invasion Emulator",
      "High-Powered Probe Technology",
      "Highpowered Lab Partner Automaton",
      "Host",
      "Humanoid Laboratorium Automaton",
      "Hydrasweep",
      "I am a Bot",
      "Imperial Decimator",
      "Independent Encryption Android",
      "Independent Troubleshooting Automaton",
      "Inevitable",
      "Inferno",
      "Integrated Nullification Android",
      "Intelligent Peacekeeping Emulator",
      "Invictus",
      "Iron Angel",
      "Iron Walker",
      "Irone",
      "Irony",
      "Jesh",
      "Junkfoot",
      "Klunk",
      "L-76",
      "LILLIPUT TOY ROBOT",
      "Lax-3",
      "Lightblades",
      "Lightthing",
      "MOBOTS",
      "MQ-1 PREDATOR",
      "Magnasteel",
      "Main Battle Entity",
      "Main Escort Technology",
      "Mechanical Examination Prototype",
      "Mechanical Oceanic Navigation Entity",
      "Mechanized Space Navigation Entity",
      "Mes",
      "Mis",
      "Mod-147a",
      "Mod-236c",
      "Mod-72x",
      "Module-157x",
      "Module-30s",
      "Motorized Instructor Technician",
      "Motorized Unit Response Cyborg",
      "Mountain",
      "Myriad Trooper",
      "Myriad",
      "Neohuman Supervision Technician",
      "Neohuman Waste Disposal Technician",
      "Neptune",
      "OPTIMUS",
      "Omega",
      "Operate-Bot",
      "Oracle",
      "Overflow",
      "PACKBOT",
      "Pala",
      "Pandora",
      "Pelican",
      "Personal Regulation Bot",
      "Phalanx",
      "Plane Panzer",
      "Platform-3a",
      "Platform-40c",
      "Polaris",
      "Preliminary Emulation Juggernaut",
      "Primary Travel Robot",
      "Prime Waste Disposal Android",
      "Primitive Caretaker Juggernaut",
      "Primitive Processor Robot",
      "Programmed Neutralization Technology",
      "Pulvi",
      "Pulvis",
      "Pursuit",
      "Quarris",
      "R-egoistic",
      "R2-D2",
      "RB5X",
      "ROBART III",
      "ROOMBA DISCOVERY",
      "Rational Emergency Android",
      "Rational Utility Technician",
      "Reactive Personal Protection Technology",
      "Reactive Processor Emulator",
      "Reactive Waste Disposal Drone",
      "Ready to Rob-OT",
      "Responsive Diplomacy Technology",
      "Responsive Planet Examination Droid",
      "Revered Command Unit",
      "Robust-tic",
      "Roughthing",
      "S-BOT",
      "SIRI",
      "SLUGBOT",
      "SPARKO",
      "Salvage Stalker",
      "Sci Bots",
      "Scoop+",
      "Seahide",
      "Secondary Excretion Golem",
      "Secondary Planet Defence Machine",
      "Secondary War Domination Bot",
      "Self-Aware Encoding Device",
      "Self-Sufficient Expedition Droid",
      "Self-Sufficient Operation Entity",
      "Selfaware Antivenom Manipulator Tool",
      "Selfaware Transport Diagnoser Apparatus",
      "Sensitive Construction Technology",
      "Sensory Diplomacy Juggernaut",
      "Shade Armor Suit",
      "Shadowblight",
      "Sideburns",
      "Sidelock",
      "Sir",
      "SliverCode",
      "Snap Engine",
      "Solar Care Technician",
      "Solar Teaching Robot",
      "Sparrow",
      "Starburst",
      "Stark",
      "Stealth Detector Apparatus",
      "Steelblast",
      "Strange Thing",
      "Super Nova",
      "Super Probe Cyborg",
      "Super Riot Control Juggernaut",
      "Supreme Escort Automaton",
      "Supreme Flora And Fauna Bot",
      "Synchronized Decoding Automaton",
      "Synchronized Evasion Golem",
      "Synchronized Processor Technician",
      "SysMod-216e",
      "SysMod-23e",
      "SysMod-81x",
      "System-65b",
      "System-83x",
      "THE IRON GIANT",
      "THE TERMINATOR",
      "Tank",
      "Temporary Termination Android",
      "Tera",
      "Terbius",
      "Terminus",
      "Terra",
      "Terrane",
      "Thait",
      "The Nawab",
      "Titan",
      "Tony",
      "Topburn",
      "Tranquility",
      "Twinbeam",
      "Twinkle",
      "Ultimate Decoding Emulator",
      "Ultimate Emergency Response Technician",
      "Ultimate Waste Disposal Droid",
      "Unified Emulation Emulator",
      "Unit-13s",
      "Unit-15a",
      "Unit-188b",
      "Unit-188s",
      "Unit-28x",
      "Unit-35x",
      "Unit-87b",
      "Universal Encryption Android",
      "Universal Exploration Golem",
      "Universal Space Exploration Golem",
      "Vector",
      "Vile Drone",
      "Viper",
      "Virtue",
      "Visage",
      "Vortex",
      "W.I.F.E",
      "Warden",
      "Whop",
      "Whopper",
      "Widow Maker",
      "You Need Me",
      "Z-1",
      "Z-2",
      "Z-3",
      "Zephyr",
      "Zodiac"
]
export default names